spring:
  application:
    name: ecommerce
  datasource:
    url: jdbc:mysql://localhost:3306/spring_ecommerce_api?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    show-sql: true

stripe:
  apiUrl: https://api.stripe.com
  enabled: true
  timeout: 1000
  supported-currencies: USD,EUR,GBP

payment-gateway: paypal

mail:
  host: 127.0.0.1
  port: 465